###
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "a@naver.com",
  "password": "1111",
  "userName": "asdfasd",
  "phoneNumber": "1112-11"

}

###
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "id": "1",
  "initialBalance": 100
}

###
POST http://localhost:8080/transaction/amount
Content-Type: application/json

{
  "accountId": 1,
  "amount": 100
}

###
POST http://localhost:8080/transaction/amount/withdraw
Content-Type: application/json

{
  "accountId": 1,
  "amount": 100
}

###
GET http://localhost:8080/accounts/1/balance